collections:
  - name: biostat
    label: 生物统计学
    folder: docs/courses/biostat/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: 发布日期, name: date, widget: datetime }
      - { label: 作者, name: authors, widget: list, default: [lei] }
      - { label: 正文, name: body, widget: markdown }

  - name: linear-algebra
    label: 线性代数
    folder: docs/courses/linear-algebra/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: 发布日期, name: date, widget: datetime }
      - { label: 作者, name: authors, widget: list, default: [lei] }
      - { label: 正文, name: body, widget: markdown }

  - name: biostat-about
    label: 生物统计学 - 课程介绍
    files:
      - label: 课程介绍
        name: about
        file: docs/courses/biostat/about.md
        fields:
          - { label: 标题, name: title, widget: string }
          - { label: 正文, name: body, widget: markdown }
  
  - name: linear-algebra-about
    label: 线性代数 - 课程介绍
    files:
      - label: 课程介绍
        name: about
        file: docs/courses/linear-algebra/about.md
        fields:
          - { label: 标题, name: title, widget: string }
          - { label: 正文, name: body, widget: markdown }
